
import React, { useState, useRef, useEffect } from 'react';
import { Upload, AlertTriangle, ArrowRight, Eye, RefreshCw, User, Clock, Speaker, TrendingUp, Activity, Layers, Loader2, MapPin, Cloud, Hexagon, BarChart3, Wind, Brain, Bus, ShoppingBag, Users, Coins, Globe, Music, FileText, CheckCircle2, Copy, PlayCircle, History, X } from 'lucide-react';
import { AnalysisStatus, EthnographyReport, FileData, HistoryItem } from './types';
import { analyzeVibe, processFileToBase64 } from './services/geminiService';
import { LoadingTerminal } from './components/LoadingTerminal';
import { AnalysisChart } from './components/AnalysisChart';
import { NoiseOverlay } from './components/NoiseOverlay';
import { VisualGrounding } from './components/VisualGrounding';
import { RadarAnalysis } from './components/RadarAnalysis';
import { GeoMap } from './components/GeoMap';
import { TrendChart } from './components/TrendChart';
import { InstantIPO } from './components/InstantIPO';
import { DatingProfiles } from './components/DatingProfiles';
import { EconomicsWidget } from './components/EconomicsWidget';
import { SoundscapePlayer } from './components/SoundscapePlayer';
import { HistorySidebar } from './components/HistorySidebar';
import { DEMO_REPORT, DEMO_IMAGE_URL } from './services/demoData';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

const TypewriterText: React.FC<{ text: string; delay?: number }> = ({ text, delay = 0 }) => {
  const [displayedText, setDisplayedText] = useState('');
  
  useEffect(() => {
    setDisplayedText(''); // Reset on text change
    
    const timeout = setTimeout(() => {
      let i = 0;
      const interval = setInterval(() => {
        setDisplayedText((prev) => text.substring(0, i + 1));
        i++;
        if (i === text.length) clearInterval(interval);
      }, 20); // Typing speed
      return () => clearInterval(interval);
    }, delay);

    return () => clearTimeout(timeout);
  }, [text, delay]);

  return <span>{displayedText}</span>;
};

// --- MULTI-PAGE PDF TEMPLATE ---
const PdfReportTemplate: React.FC<{ report: EthnographyReport, fileData: FileData }> = ({ report, fileData }) => {
    const PageHeader = ({ title, pageNum }: { title: string, pageNum: string }) => (
        <div className="flex justify-between items-end border-b-2 border-white mb-8 pb-4 shrink-0">
            <div>
                <h1 className="text-4xl font-bold tracking-tighter mb-2">VIBE_OS // {title}</h1>
                <div className="flex gap-4 font-mono text-xs text-signal-orange">
                    <span>CONFIDENTIAL DOSSIER</span>
                    <span>LOC: {report.coordinates.locationName.toUpperCase()}</span>
                </div>
            </div>
            <div className="text-right font-mono text-[10px] text-gray-500">
                <div>CASE_ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}</div>
                <div>PAGE {pageNum}/04</div>
            </div>
        </div>
    );

    const PageFooter = () => (
        <div className="mt-auto pt-6 border-t border-gray-800 flex justify-between items-center text-[10px] text-gray-600 font-mono shrink-0">
             <span>GENERATED BY GEMINI 3 PRO // VIBE_OS V4.2</span>
             <span>{new Date().toLocaleDateString().toUpperCase()}</span>
        </div>
    );

    return (
        <div id="pdf-report-root">
            {/* PAGE 1: EXECUTIVE SUMMARY & VISUALS */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <div className="absolute inset-0 flex items-center justify-center opacity-[0.02] pointer-events-none">
                     <h1 className="text-[300px] font-bold -rotate-45">VIBE</h1>
                </div>
                
                <PageHeader title="VISUAL INTEL" pageNum="01" />

                <div className="flex-grow flex flex-col gap-8">
                    {/* Hero Visual */}
                    <div className="h-[650px] border border-gray-700 bg-black relative shadow-2xl">
                         <VisualGrounding fileData={fileData} boxes={report.detectedObjects} staticMode={true} />
                         <div className="absolute bottom-0 left-0 right-0 bg-black/80 backdrop-blur-md p-4 border-t border-gray-700 flex justify-between items-center">
                             <div>
                                 <span className="text-[10px] font-mono text-gray-500 block">VIBE CODE</span>
                                 <span className="text-xl font-bold text-white uppercase">{report.locationVibe}</span>
                             </div>
                         </div>
                    </div>

                    {/* Key Indices */}
                    <div className="grid grid-cols-3 gap-6">
                        <div className="bg-gray-900/50 p-6 border border-gray-700 backdrop-blur-sm">
                             <div className="text-xs text-gray-500 font-mono mb-2">VIABILITY SCORE</div>
                             <div className="text-7xl font-bold text-signal-green tracking-tighter">{report.viabilityScore}</div>
                        </div>
                        <div className="bg-gray-900/50 p-6 border border-gray-700 backdrop-blur-sm">
                             <div className="text-xs text-gray-500 font-mono mb-2">GENTRIFICATION</div>
                             <div className="text-7xl font-bold text-signal-orange tracking-tighter">{report.gentrificationIndex}</div>
                        </div>
                        <div className="bg-gray-900/50 p-6 border border-gray-700 backdrop-blur-sm">
                             <div className="text-xs text-gray-500 font-mono mb-2">SOCIAL INDEX</div>
                             <div className="text-7xl font-bold text-white tracking-tighter">{report.socialScore}</div>
                        </div>
                    </div>
                </div>
                <PageFooter />
            </div>

            {/* PAGE 2: ENVIRONMENTAL SCAN */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <PageHeader title="ENVIRONMENT" pageNum="02" />
                
                <div className="grid grid-cols-2 gap-10 flex-grow">
                    <div className="flex flex-col gap-8">
                        {/* Map */}
                        <div className="border border-gray-700 h-[400px] bg-gray-900 relative">
                             {/* Note: Leaflet might not capture perfectly in hidden div, so we rely on the component or a fallback if needed. Usually it works with useCORS. */}
                             <GeoMap coordinates={report.coordinates} />
                             <div className="absolute bottom-2 left-2 bg-black/80 px-2 py-1 text-[10px] font-mono text-signal-green">
                                 LAT: {report.coordinates.lat} / LON: {report.coordinates.lng}
                             </div>
                        </div>

                        {/* Radar */}
                        <div className="border border-gray-700 p-6 bg-gray-900/30">
                            <h3 className="font-mono text-xs text-gray-500 mb-6 uppercase tracking-widest border-b border-gray-800 pb-2">Vibe Metrics</h3>
                            <div className="h-[300px]">
                                <RadarAnalysis metrics={report.radarMetrics} />
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col gap-6">
                         {/* Stats Grid */}
                         <div className="grid grid-cols-2 gap-4">
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Architecture</span>
                                <span className="text-sm font-bold">{report.architecturalStyle}</span>
                            </div>
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Atmosphere</span>
                                <span className="text-sm font-bold">{report.atmosphere}</span>
                            </div>
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Density</span>
                                <span className="text-sm font-bold">{report.commercialDensity}</span>
                            </div>
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Status</span>
                                <span className="text-sm font-bold">{report.constructionStatus}</span>
                            </div>
                         </div>
                         
                         {/* New Economics Widget for PDF */}
                         <EconomicsWidget latteIndex={report.latteIndex} panopticon={report.panopticonScore} goldenHour={report.goldenHour} />

                         {/* Temporal */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30">
                             <h3 className="font-mono text-xs text-gray-500 mb-6 uppercase tracking-widest border-b border-gray-800 pb-2">Time Travel</h3>
                             <div className="space-y-6">
                                <div>
                                    <span className="text-[10px] text-gray-500 font-mono block mb-2">PAST (-10 YEARS)</span>
                                    <p className="text-sm leading-relaxed border-l-2 border-gray-600 pl-4 text-gray-300">{report.temporalProjection.past}</p>
                                </div>
                                <div>
                                    <span className="text-[10px] text-gray-500 font-mono block mb-2">FUTURE (+10 YEARS)</span>
                                    <p className="text-sm leading-relaxed border-l-2 border-signal-orange pl-4 text-white">{report.temporalProjection.future}</p>
                                </div>
                             </div>
                         </div>
                    </div>
                </div>
                <PageFooter />
            </div>

            {/* PAGE 3: STRATEGY */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <PageHeader title="STRATEGY" pageNum="03" />
                
                <div className="flex-grow flex flex-col gap-8">
                    {/* The Big Idea - Now using InstantIPO component layout simplified for PDF */}
                    <div className="bg-gray-900 border border-gray-700 p-10 relative overflow-hidden">
                         <InstantIPO recommendation={report.businessRecommendation} />
                    </div>

                    <div className="grid grid-cols-2 gap-8 h-[400px]">
                         {/* Financials */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30 flex flex-col justify-between">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Real Estate Intel</h3>
                             <div className="space-y-6">
                                 <div>
                                     <span className="text-xs text-gray-500">ESTIMATED RENT</span>
                                     <div className="text-3xl font-bold">{report.rentalOpportunity.estimatedRentPerSqFt}</div>
                                 </div>
                                 <div>
                                     <span className="text-xs text-gray-500">VACANCY RISK</span>
                                     <div className={`text-2xl font-bold ${report.rentalOpportunity.vacancyRisk === 'HIGH' ? 'text-red-500' : 'text-green-500'}`}>{report.rentalOpportunity.vacancyRisk}</div>
                                 </div>
                                 <div className="h-24">
                                     <span className="text-xs text-gray-500 block mb-2">GROWTH TREND</span>
                                     <TrendChart />
                                 </div>
                             </div>
                         </div>

                         {/* Pitch */}
                         <div className="border border-gray-700 p-6 bg-white/5">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Investor Pitch</h3>
                             <div className="font-mono text-[11px] text-gray-300 leading-relaxed bg-black p-6 border border-gray-800 h-full overflow-hidden">
                                 <div className="mb-4 text-gray-500 border-b border-gray-800 pb-2">Subject: {report.investorPitch.subjectLine}</div>
                                 {report.investorPitch.emailBody}
                             </div>
                         </div>
                    </div>
                </div>
                <PageFooter />
            </div>

            {/* PAGE 4: CULTURE */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <PageHeader title="CULTURAL DNA" pageNum="04" />
                
                <div className="flex-grow grid grid-cols-2 gap-10">
                     <div className="flex flex-col gap-8">
                         {/* Persona */}
                         <div className="border border-gray-700 p-8 bg-gray-900 relative overflow-hidden">
                             <User className="absolute top-4 right-4 w-12 h-12 text-gray-800" />
                             <span className="text-signal-orange font-mono text-xs tracking-widest uppercase mb-2 block">Target Persona</span>
                             <h2 className="text-3xl font-bold text-white mb-4">{report.targetPersona.archetype}</h2>
                             <p className="font-serif italic text-xl text-gray-400 mb-6 leading-relaxed">"{report.targetPersona.quote}"</p>
                             <div className="flex flex-wrap gap-2">
                                 {report.targetPersona.accessories.map((item, i) => (
                                     <span key={i} className="px-3 py-1 bg-black border border-gray-700 rounded-full text-xs text-gray-300">{item}</span>
                                 ))}
                             </div>
                         </div>
                         
                         <DatingProfiles profiles={report.datingProfiles} />

                         {/* Demographics */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30 flex-grow">
                             <span className="text-gray-500 font-mono text-xs tracking-widest uppercase mb-4 block">Demographic Split</span>
                             <AnalysisChart data={report.observedDemographics} />
                         </div>
                     </div>

                     <div className="flex flex-col gap-8">
                         {/* Sonic Identity */}
                         <div className="border border-gray-700 p-8 bg-gray-900/50">
                             <h3 className="font-mono text-xs text-gray-500 mb-6 uppercase tracking-widest border-b border-gray-800 pb-2">Sonic Identity</h3>
                             <div className="space-y-6">
                                 {report.playlist.map((track, i) => (
                                     <div key={i} className="flex items-center gap-4">
                                         <div className="w-8 h-8 rounded-full bg-gray-800 flex items-center justify-center text-xs font-mono text-gray-500">{i+1}</div>
                                         <div>
                                             <div className="font-bold text-lg">{track.song}</div>
                                             <div className="text-sm text-gray-400">{track.artist}</div>
                                             <div className="text-[10px] text-signal-orange font-mono uppercase mt-1">{track.vibe}</div>
                                         </div>
                                     </div>
                                 ))}
                             </div>
                         </div>

                         {/* Sensory */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Sensory Profile</h3>
                             <div className="space-y-4">
                                 <div>
                                     <span className="text-[10px] text-gray-500 font-mono block mb-1">SCENT</span>
                                     <p className="text-sm text-white">{report.scentProfile.join(', ')}</p>
                                 </div>
                                 <div>
                                     <span className="text-[10px] text-gray-500 font-mono block mb-1">SOUNDSCAPE</span>
                                     <p className="text-sm text-white">{report.soundscape.join(', ')}</p>
                                 </div>
                             </div>
                         </div>
                         
                         {/* Color Palette */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Vibe Palette</h3>
                             <div className="flex h-12 w-full">
                                 {report.colorPalette.map((color, i) => (
                                     <div key={i} className="h-full flex-1" style={{ backgroundColor: color }}></div>
                                 ))}
                             </div>
                         </div>
                     </div>
                </div>
                <PageFooter />
            </div>
        </div>
    );
};


const App: React.FC = () => {
  const [status, setStatus] = useState<AnalysisStatus>(AnalysisStatus.IDLE);
  const [fileData, setFileData] = useState<FileData | null>(null);
  const [report, setReport] = useState<EthnographyReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [activeTab, setActiveTab] = useState<'OVERVIEW' | 'BUSINESS' | 'CULTURE'>('OVERVIEW');
  const [pitchCopied, setPitchCopied] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Load history on mount
  useEffect(() => {
      try {
          const savedHistory = localStorage.getItem('vibe_history');
          if (savedHistory) {
              setHistory(JSON.parse(savedHistory));
          }
      } catch (e) {
          console.error("Failed to load history", e);
      }
  }, []);

  const addToHistory = (reportToAdd: EthnographyReport, fileToAdd: FileData) => {
      // Create a thumbnail (using preview URL or truncated base64 if needed, 
      // but simple URL doesn't persist, so we rely on base64 if available, or just placeholder for demo)
      
      // Limit history to last 5 items to avoid LocalStorage quota issues
      const newItem: HistoryItem = {
          id: Date.now().toString(),
          timestamp: Date.now(),
          report: reportToAdd,
          thumbnail: fileToAdd.base64 ? `data:${fileToAdd.mimeType};base64,${fileToAdd.base64}` : '' // Might be too large, but trying for now.
      };

      // Simple size check hack - if too big, don't save thumbnail
      if (newItem.thumbnail.length > 2000000) {
          newItem.thumbnail = ''; // Too big for localstorage usually
      }

      const updatedHistory = [newItem, ...history].slice(0, 5);
      setHistory(updatedHistory);
      localStorage.setItem('vibe_history', JSON.stringify(updatedHistory));
  };
  
  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      const file = event.target.files[0];
      if (file.size > 50 * 1024 * 1024) {
        setError("File too large. Please upload media under 50MB.");
        return;
      }

      const previewUrl = URL.createObjectURL(file);
      setFileData({
        file,
        previewUrl,
        base64: '',
        mimeType: file.type
      });
      setStatus(AnalysisStatus.IDLE);
      setError(null);
    }
  };

  const startAnalysis = async () => {
    if (!fileData) return;
    setStatus(AnalysisStatus.PROCESSING);
    
    try {
      // We need base64 for history saving later
      const base64 = await processFileToBase64(fileData.file);
      // Update fileData with base64
      const updatedFileData = { ...fileData, base64 };
      setFileData(updatedFileData);

      const result = await analyzeVibe(fileData.file);
      setReport(result);
      setStatus(AnalysisStatus.COMPLETE);
      
      // Save to History
      addToHistory(result, updatedFileData);

    } catch (err) {
      console.error(err);
      setError("Analysis failed. The ethnography engine encountered an anomaly.");
      setStatus(AnalysisStatus.ERROR);
    }
  };

  const loadDemo = async () => {
    setStatus(AnalysisStatus.PROCESSING);
    setTimeout(() => {
        const file = new File([""], "demo_shoreditch.jpg", { type: "image/jpeg" });
        const demoFileData = {
            file,
            previewUrl: DEMO_IMAGE_URL,
            base64: "", // Demo data doesn't have real base64
            mimeType: "image/jpeg"
        };
        setFileData(demoFileData);
        setReport(DEMO_REPORT);
        setStatus(AnalysisStatus.COMPLETE);
        // Not saving demo to history to keep it clean, or could save if desired
    }, 2500);
  };

  const loadFromHistory = (item: HistoryItem) => {
      // Create a dummy file object since we lost it
      const file = new File([""], "history_item", { type: "image/jpeg" });
      setFileData({
          file,
          previewUrl: item.thumbnail || '', // If no thumbnail, might be blank
          base64: item.thumbnail?.split(',')[1] || '',
          mimeType: "image/jpeg" // Assumption
      });
      setReport(item.report);
      setStatus(AnalysisStatus.COMPLETE);
      setShowHistory(false);
  };

  const reset = () => {
    setFileData(null);
    setReport(null);
    setStatus(AnalysisStatus.IDLE);
    setError(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleExportPDF = async () => {
    const pages = document.querySelectorAll('.pdf-page');
    if (!pages.length) return;
    
    setIsExporting(true);

    try {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [1000, 1414] 
      });

      for (let i = 0; i < pages.length; i++) {
          const page = pages[i] as HTMLElement;
          const canvas = await html2canvas(page, {
            scale: 2,
            backgroundColor: '#0a0a0a',
            useCORS: true,
            logging: false,
            allowTaint: true
          });

          const imgData = canvas.toDataURL('image/png');
          
          if (i > 0) {
              pdf.addPage([1000, 1414]);
          }
          pdf.addImage(imgData, 'PNG', 0, 0, 1000, 1414);
      }

      pdf.save(`VibeOS_Dossier_${Date.now()}.pdf`);

    } catch (err) {
      console.error("PDF Export failed:", err);
      setError("Failed to generate PDF visualization.");
    } finally {
      setIsExporting(false);
    }
  };

  const copyPitch = () => {
      if(report) {
          navigator.clipboard.writeText(`Subject: ${report.investorPitch.subjectLine}\n\n${report.investorPitch.emailBody}`);
          setPitchCopied(true);
          setTimeout(() => setPitchCopied(false), 2000);
      }
  };

  return (
    <div className="min-h-screen font-sans bg-anthro-black text-anthro-light selection:bg-signal-orange selection:text-anthro-black overflow-x-hidden relative">
      <NoiseOverlay />
      
      <HistorySidebar 
         isOpen={showHistory} 
         onClose={() => setShowHistory(false)} 
         history={history} 
         onLoad={loadFromHistory} 
      />

      {/* HIDDEN PDF TEMPLATE (Off-screen) */}
      {report && fileData && (
          <div className="fixed top-0 left-[-9999px] z-[-100] overflow-hidden">
              <PdfReportTemplate report={report} fileData={fileData} />
          </div>
      )}
      
      {/* State: IDLE / UPLOAD */}
      {!report && status !== AnalysisStatus.ANALYZING && status !== AnalysisStatus.PROCESSING && (
         <main className="pt-12 pb-20 px-6 max-w-7xl mx-auto min-h-screen flex flex-col relative z-10">
          <div className="absolute top-6 right-6">
              <button 
                onClick={() => setShowHistory(true)}
                className="flex items-center gap-2 text-[10px] font-mono text-gray-400 hover:text-white transition-colors"
              >
                  <History className="w-4 h-4" /> HISTORY
              </button>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center flex-grow">
            <div className="space-y-8 animate-in fade-in slide-in-from-left duration-700">
              <div className="space-y-4">
                <div className="inline-block px-2 py-1 border border-signal-orange text-signal-orange text-[10px] font-mono tracking-widest uppercase mb-2">
                  VIBE_OS // V4.2
                </div>
                <h2 className="text-5xl md:text-7xl font-bold tracking-tighter leading-[0.9]">
                  Decode the street.<br/>
                  <span className="text-gray-700">Predict the wealth.</span>
                </h2>
                <p className="text-gray-400 text-lg max-w-md leading-relaxed">
                  The first <strong>Visual Ethnography Engine</strong> powered by Gemini 3 Pro. We analyze fashion, architecture, and entropy to generate institutional-grade business intelligence.
                </p>
                
                <button 
                  onClick={loadDemo}
                  className="mt-6 flex items-center gap-3 bg-white/5 hover:bg-white/10 border border-white/20 text-white px-6 py-3 transition-all rounded-sm group"
                >
                  <PlayCircle className="w-5 h-5 text-signal-green group-hover:scale-110 transition-transform" />
                  <span className="font-mono text-sm tracking-wide">TRY LIVE DEMO (LONDON)</span>
                </button>
              </div>
              
              {error && (
                <div className="flex items-center gap-2 text-red-500 font-mono text-xs border border-red-900/50 bg-red-900/10 p-3">
                   <AlertTriangle className="w-4 h-4" /> {error}
                </div>
              )}
            </div>

            <div className="h-full flex flex-col justify-center animate-in fade-in slide-in-from-right duration-700 delay-200">
              <div className="w-full min-h-[400px] lg:min-h-[500px] border border-dashed border-gray-700 bg-anthro-gray/30 hover:bg-anthro-gray/50 transition-colors group relative overflow-hidden flex flex-col items-center justify-center">
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handleFileSelect}
                  accept="image/*,video/*"
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                />
                
                {!fileData ? (
                  <div className="flex flex-col items-center justify-center gap-6 p-8 text-center pointer-events-none">
                    <div className="w-24 h-24 border border-gray-600 rounded-full flex items-center justify-center group-hover:scale-110 transition-transform duration-500 bg-black/50 backdrop-blur-sm shadow-2xl">
                       <Upload className="w-8 h-8 text-gray-400 group-hover:text-white transition-colors" />
                    </div>
                    <div className="space-y-2">
                      <p className="font-mono text-lg text-gray-300 tracking-wider">INITIATE SCAN</p>
                      <p className="text-xs text-gray-600 font-mono">UPLOAD FOOTAGE (MAX 50MB)</p>
                    </div>
                  </div>
                ) : (
                  <div className="absolute inset-0 w-full h-full bg-black flex items-center justify-center overflow-hidden">
                     {fileData.mimeType.startsWith('video') ? (
                       <video 
                        src={fileData.previewUrl} 
                        className="w-full h-full object-cover opacity-60"
                        loop 
                        autoPlay 
                        muted 
                        playsInline
                       />
                     ) : (
                       <img src={fileData.previewUrl} alt="Preview" className="w-full h-full object-cover opacity-60" />
                     )}
                     <div className="absolute inset-0 bg-gradient-to-t from-anthro-black via-transparent to-transparent" />
                     
                     <div className="absolute top-4 right-4 flex flex-col items-end gap-1">
                        <span className="text-[10px] font-mono text-signal-orange bg-black/50 px-2 py-1">SOURCE_LOCKED</span>
                        <span className="text-[10px] font-mono text-gray-400">{fileData.file.name}</span>
                     </div>

                     <div className="absolute bottom-8 left-0 right-0 flex justify-center z-20 pointer-events-none">
                        <button 
                            onClick={(e) => {
                                startAnalysis();
                            }}
                            className="pointer-events-auto bg-signal-orange hover:bg-orange-600 text-anthro-black font-bold px-10 py-4 flex items-center gap-2 transition-all hover:scale-105 shadow-[0_0_30px_rgba(255,77,0,0.4)] tracking-widest text-sm"
                        >
                            RUN VIBE_OS <ArrowRight className="w-4 h-4" />
                        </button>
                     </div>
                  </div>
                )}
              </div>
            </div>
          </div>
         </main>
      )}

      {/* State: PROCESSING */}
      {status === AnalysisStatus.PROCESSING && (
           <div className="fixed inset-0 z-50 bg-anthro-black flex flex-col items-center justify-center">
             <LoadingTerminal />
           </div>
      )}

      {/* State: REPORT (DASHBOARD MODE) */}
      {status === AnalysisStatus.COMPLETE && report && fileData && (
        <div className="h-screen flex flex-col overflow-hidden animate-in fade-in duration-1000">
             {/* TOP BAR */}
             <div className="h-14 border-b border-gray-800 bg-anthro-black flex items-center justify-between px-6 shrink-0 z-50">
                <div className="flex items-center gap-6">
                    <span className="font-bold tracking-tighter text-xl">VIBE_OS</span>
                    <div className="h-4 w-[1px] bg-gray-700"></div>
                    <div className="flex items-center gap-2 text-[10px] font-mono text-signal-green">
                        <div className="w-2 h-2 rounded-full bg-signal-green animate-pulse"></div>
                        LIVE ANALYSIS
                    </div>
                </div>
                <div className="flex gap-2">
                     <button onClick={() => setShowHistory(true)} className="flex items-center gap-2 px-3 py-1.5 text-[10px] font-mono border border-gray-700 hover:bg-gray-800 transition-colors text-gray-400">
                        <History className="w-3 h-3" />
                     </button>
                     <button onClick={handleExportPDF} disabled={isExporting} className="flex items-center gap-2 px-3 py-1.5 text-[10px] font-mono border border-gray-700 hover:bg-gray-800 transition-colors">
                        {isExporting ? <Loader2 className="w-3 h-3 animate-spin" /> : <Layers className="w-3 h-3" />}
                        EXPORT DOSSIER
                     </button>
                     <button onClick={reset} className="flex items-center gap-2 px-3 py-1.5 text-[10px] font-mono bg-white text-black hover:bg-gray-200 transition-colors">
                        <RefreshCw className="w-3 h-3" />
                        NEW SCAN
                     </button>
                </div>
             </div>

             {/* MAIN CONTENT SPLIT */}
             <div className="flex-grow flex flex-col lg:flex-row overflow-hidden">
                
                {/* LEFT: VISUAL (Sticky) */}
                <div className="lg:w-[45%] h-[40vh] lg:h-full border-r border-gray-800 bg-black relative flex flex-col">
                    <div className="flex-grow relative overflow-hidden bg-black flex items-center justify-center">
                        <VisualGrounding fileData={fileData} boxes={report.detectedObjects} />
                    </div>
                    {/* MINI METRICS UNDER VISUAL */}
                    <div className="h-auto p-4 bg-anthro-gray/20 border-t border-gray-800 grid grid-cols-2 gap-4 shrink-0">
                         <div>
                            <span className="text-[9px] font-mono text-gray-500 block mb-1">LOCATION VIBE</span>
                            <div className="text-xl font-bold leading-none uppercase text-white">
                                <TypewriterText text={report.locationVibe} delay={500} />
                            </div>
                         </div>
                         <div className="flex justify-end items-end">
                            <div className="text-right">
                                <span className="text-[9px] font-mono text-gray-500 block mb-1">VIABILITY INDEX</span>
                                <span className={`text-2xl font-bold ${report.viabilityScore > 75 ? 'text-signal-green' : 'text-signal-orange'}`}>{report.viabilityScore}/100</span>
                            </div>
                         </div>
                    </div>
                </div>

                {/* RIGHT: DATA DASHBOARD (Scrollable) */}
                <div className="lg:w-[55%] h-full flex flex-col bg-anthro-black overflow-y-auto">
                    
                    {/* TABS */}
                    <div className="flex border-b border-gray-800 sticky top-0 bg-anthro-black z-40">
                        {(['OVERVIEW', 'BUSINESS', 'CULTURE'] as const).map(tab => (
                            <button 
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`flex-1 py-4 text-xs font-mono tracking-widest border-b-2 transition-colors ${activeTab === tab ? 'border-signal-orange text-white' : 'border-transparent text-gray-600 hover:text-gray-400'}`}
                            >
                                {tab}
                            </button>
                        ))}
                    </div>

                    {/* TAB CONTENT */}
                    <div className="p-6 space-y-6 pb-20">
                        
                        {/* ---------------- OVERVIEW TAB ---------------- */}
                        {activeTab === 'OVERVIEW' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                                {/* Map & Matches Row */}
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 h-64">
                                    <div className="h-full">
                                        <GeoMap coordinates={report.coordinates} />
                                    </div>
                                    <div className="h-full overflow-y-auto pr-2 space-y-3 scrollbar-thin">
                                        <h4 className="text-[10px] font-mono text-gray-500 uppercase sticky top-0 bg-anthro-black pb-2">Global Vibe Matches</h4>
                                        {report.vibeMatches.map((match, i) => (
                                            <div key={i} className="bg-anthro-gray/10 border border-gray-800 p-4 hover:border-gray-600 transition-colors">
                                                <div className="flex items-center gap-2 mb-2">
                                                    <Globe className="w-3 h-3 text-gray-500" />
                                                    <span className="text-[10px] font-mono text-gray-400">VIBE TWIN {i+1}</span>
                                                </div>
                                                <div className="font-bold text-sm text-white mb-1">{match.location}, {match.city}</div>
                                                <div className="w-full bg-gray-800 h-1 mt-2">
                                                    <div className="h-full bg-signal-green" style={{width: `${match.matchScore}%`}}></div>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                {/* Environmental Grid */}
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                     <div className="bg-anthro-gray/10 p-4 border border-gray-800 flex flex-col items-center justify-center text-center h-32">
                                         <Hexagon className="w-5 h-5 text-gray-500 mb-2" />
                                         <span className="text-[9px] font-mono text-gray-500 block mb-1">ARCHITECTURE</span>
                                         <span className="text-xs font-bold leading-tight">{report.architecturalStyle}</span>
                                     </div>
                                     <div className="bg-anthro-gray/10 p-4 border border-gray-800 flex flex-col items-center justify-center text-center h-32">
                                         <Cloud className="w-5 h-5 text-gray-500 mb-2" />
                                         <span className="text-[9px] font-mono text-gray-500 block mb-1">ATMOSPHERE</span>
                                         <span className="text-xs font-bold leading-tight">{report.atmosphere}</span>
                                     </div>
                                     <div className="bg-anthro-gray/10 p-4 border border-gray-800 flex flex-col items-center justify-center text-center h-32">
                                         <BarChart3 className="w-5 h-5 text-gray-500 mb-2" />
                                         <span className="text-[9px] font-mono text-gray-500 block mb-1">DENSITY</span>
                                         <span className="text-xs font-bold leading-tight">{report.commercialDensity}</span>
                                     </div>
                                     <div className="bg-anthro-gray/10 p-4 border border-gray-800 flex flex-col items-center justify-center text-center h-32">
                                         <Activity className="w-5 h-5 text-gray-500 mb-2" />
                                         <span className="text-[9px] font-mono text-gray-500 block mb-1">GENTRIFICATION</span>
                                         <span className="text-xl font-bold text-signal-orange">{report.gentrificationIndex}</span>
                                     </div>
                                </div>
                                
                                <EconomicsWidget latteIndex={report.latteIndex} panopticon={report.panopticonScore} goldenHour={report.goldenHour} />

                                {/* Radar */}
                                <div className="bg-anthro-gray/10 border border-gray-800 p-4">
                                    <h3 className="font-mono text-[10px] text-gray-500 mb-4 flex items-center gap-2 uppercase">
                                        Vibe Metrics
                                    </h3>
                                    <RadarAnalysis metrics={report.radarMetrics} />
                                </div>

                                {/* Temporal */}
                                <div className="border border-gray-800 p-4 bg-black/40">
                                     <div className="flex items-center gap-2 text-signal-orange mb-3">
                                         <Clock className="w-3 h-3" />
                                         <span className="text-[10px] font-mono tracking-wider">TEMPORAL PROJECTION</span>
                                     </div>
                                     <div className="flex flex-col md:flex-row gap-6">
                                         <div className="flex-1">
                                             <span className="text-[9px] text-gray-600 block mb-1 font-mono">PAST (-10 YRS)</span>
                                             <p className="text-xs text-gray-400 border-l border-gray-800 pl-3 pt-1">{report.temporalProjection.past}</p>
                                         </div>
                                         <div className="flex-1">
                                             <span className="text-[9px] text-gray-600 block mb-1 font-mono">FUTURE (+10 YRS)</span>
                                             <p className="text-xs text-gray-300 border-l border-signal-orange pl-3 pt-1">{report.temporalProjection.future}</p>
                                         </div>
                                     </div>
                                </div>
                            </div>
                        )}

                        {/* ---------------- BUSINESS TAB ---------------- */}
                        {activeTab === 'BUSINESS' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                                {/* The Instant IPO - Replaces text only recommendation */}
                                <InstantIPO recommendation={report.businessRecommendation} />

                                {/* Trend Chart */}
                                <div className="bg-anthro-gray/10 border border-gray-800 p-4">
                                    <h4 className="text-[10px] font-mono text-gray-500 uppercase mb-4 flex items-center gap-2">
                                        <TrendingUp className="w-3 h-3" /> Growth Projection (5 YR)
                                    </h4>
                                    <TrendChart />
                                </div>

                                {/* Real Estate Data */}
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div className="bg-anthro-gray/10 border border-gray-800 p-4">
                                        <h4 className="text-[10px] font-mono text-gray-500 uppercase mb-4 flex items-center gap-2">
                                            <Coins className="w-3 h-3" /> Real Estate Intelligence
                                        </h4>
                                        <div className="space-y-4">
                                            <div className="flex justify-between items-center border-b border-gray-800 pb-2">
                                                <span className="text-xs text-gray-400">Est. Rent / SqFt</span>
                                                <span className="text-sm font-bold text-white">{report.rentalOpportunity.estimatedRentPerSqFt}</span>
                                            </div>
                                            <div className="flex justify-between items-center border-b border-gray-800 pb-2">
                                                <span className="text-xs text-gray-400">Vacancy Risk</span>
                                                <span className={`text-[10px] px-2 py-0.5 font-bold ${report.rentalOpportunity.vacancyRisk === 'HIGH' ? 'bg-red-900 text-red-200' : 'bg-green-900 text-green-200'}`}>
                                                    {report.rentalOpportunity.vacancyRisk}
                                                </span>
                                            </div>
                                            <div className="flex justify-between items-center border-b border-gray-800 pb-2">
                                                <span className="text-xs text-gray-400">Permit Difficulty</span>
                                                <span className="text-xs text-white">{report.rentalOpportunity.permitDifficulty}</span>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Investor Pitch */}
                                    <div className="bg-anthro-gray/10 border border-gray-800 p-4 flex flex-col">
                                        <h4 className="text-[10px] font-mono text-gray-500 uppercase mb-4 flex items-center gap-2">
                                            <FileText className="w-3 h-3" /> The Pitch
                                        </h4>
                                        <div className="flex-grow bg-black/40 p-3 text-xs text-gray-400 font-mono leading-relaxed mb-4 border border-gray-800">
                                            {report.investorPitch.emailBody}
                                        </div>
                                        <button 
                                            onClick={copyPitch}
                                            className="w-full bg-white text-black py-2 text-xs font-bold flex items-center justify-center gap-2 hover:bg-gray-200 transition-colors"
                                        >
                                            {pitchCopied ? <CheckCircle2 className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                                            {pitchCopied ? 'COPIED TO CLIPBOARD' : 'COPY INVESTOR EMAIL'}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* ---------------- CULTURE TAB ---------------- */}
                        {activeTab === 'CULTURE' && (
                            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {/* Persona */}
                                    <div className="bg-anthro-gray/20 border border-gray-800 p-6">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="w-8 h-8 rounded-full bg-gray-800 flex items-center justify-center border border-gray-600">
                                                <User className="w-4 h-4 text-gray-300" />
                                            </div>
                                            <div>
                                                <h3 className="font-mono text-xs text-gray-500 uppercase">Target Persona</h3>
                                                <p className="text-lg font-bold text-white">{report.targetPersona.archetype}</p>
                                            </div>
                                        </div>
                                        <p className="font-serif italic text-gray-400 text-sm leading-relaxed mb-4">"{report.targetPersona.quote}"</p>
                                        <div className="flex flex-wrap gap-2">
                                            {report.targetPersona.accessories.map((item, i) => (
                                                <span key={i} className="text-[10px] text-gray-300 bg-black/50 px-2 py-1 border border-gray-800 rounded-full">
                                                    {item}
                                                </span>
                                            ))}
                                        </div>
                                    </div>

                                    {/* Dating Profiles */}
                                    <DatingProfiles profiles={report.datingProfiles} />
                                 </div>
                                 
                                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {/* Sonic Identity */}
                                    <div className="space-y-4">
                                        <SoundscapePlayer metrics={report.radarMetrics} vibeDescription={report.locationVibe} />

                                        <div className="bg-anthro-gray/10 border border-gray-800 p-4">
                                             <h4 className="text-[10px] font-mono text-gray-500 uppercase mb-3 flex items-center gap-2">
                                                 <Music className="w-3 h-3" /> Playlist Recommendation
                                             </h4>
                                             <div className="space-y-2">
                                                 {report.playlist.map((track, i) => (
                                                     <div key={i} className="flex items-center justify-between border-b border-gray-800 pb-2 last:border-0">
                                                         <div>
                                                             <span className="text-xs text-white block font-bold">{track.song}</span>
                                                             <span className="text-[10px] text-gray-500">{track.artist}</span>
                                                         </div>
                                                         <span className="text-[9px] text-gray-600 font-mono uppercase">{track.vibe}</span>
                                                     </div>
                                                 ))}
                                             </div>
                                        </div>
                                        <div className="bg-anthro-gray/10 border border-gray-800 p-4">
                                            <div className="flex items-center gap-2 mb-2 text-[10px] font-mono text-gray-500">
                                                <Wind className="w-3 h-3" /> SCENT PROFILE
                                            </div>
                                            <p className="text-xs text-gray-300">{report.scentProfile.join(' • ')}</p>
                                        </div>
                                    </div>
                                    
                                    {/* Demographics Chart */}
                                    <div className="bg-anthro-gray/10 border border-gray-800 p-4">
                                        <h4 className="text-[10px] font-mono text-gray-500 uppercase mb-4">Observed Demographics</h4>
                                        <AnalysisChart data={report.observedDemographics} />
                                    </div>
                                 </div>

                                  {/* Psychogeography */}
                                  <div className="flex gap-2 items-center overflow-x-auto pb-2 scrollbar-thin">
                                    {report.psychogeography.map((mood, i) => (
                                        <div key={i} className="flex-shrink-0 border border-gray-800 bg-black/50 px-4 py-2 flex items-center gap-2">
                                            <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse"></div>
                                            <span className="text-[10px] font-mono uppercase tracking-widest text-gray-300">{mood}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                    </div>
                </div>
             </div>
        </div>
      )}
    </div>
  );
};

export default App;
