import React from 'react';
import { EthnographyReport, FileData } from '../types';
import { VisualGrounding } from './VisualGrounding';
import { GeoMap } from './GeoMap';
import { RadarAnalysis } from './RadarAnalysis';
import { EconomicsWidget } from './EconomicsWidget';
import { InstantIPO } from './InstantIPO';
import { TrendChart } from './TrendChart';
import { AnalysisChart } from './AnalysisChart';
import { DatingProfiles } from './DatingProfiles';
import { User, Music } from 'lucide-react';

interface Props {
  report: EthnographyReport;
  fileData: FileData;
}

export const PdfReportTemplate: React.FC<Props> = ({ report, fileData }) => {
    const PageHeader = ({ title, pageNum }: { title: string, pageNum: string }) => (
        <div className="flex justify-between items-end border-b-2 border-white mb-8 pb-4 shrink-0">
            <div>
                <h1 className="text-4xl font-bold tracking-tighter mb-2">VIBE_OS // {title}</h1>
                <div className="flex gap-4 font-mono text-xs text-signal-orange">
                    <span>CONFIDENTIAL DOSSIER</span>
                    <span>LOC: {report.coordinates.locationName.toUpperCase()}</span>
                </div>
            </div>
            <div className="text-right font-mono text-[10px] text-gray-500">
                <div>CASE_ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}</div>
                <div>PAGE {pageNum}/04</div>
            </div>
        </div>
    );

    const PageFooter = () => (
        <div className="mt-auto pt-6 border-t border-gray-800 flex justify-between items-center text-[10px] text-gray-600 font-mono shrink-0">
             <span>GENERATED BY GEMINI 3 PRO // VIBE_OS V4.2</span>
             <span>{new Date().toLocaleDateString().toUpperCase()}</span>
        </div>
    );

    return (
        <div id="pdf-report-root">
            {/* PAGE 1: EXECUTIVE SUMMARY & VISUALS */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <div className="absolute inset-0 flex items-center justify-center opacity-[0.02] pointer-events-none">
                     <h1 className="text-[300px] font-bold -rotate-45">VIBE</h1>
                </div>
                
                <PageHeader title="VISUAL INTEL" pageNum="01" />

                <div className="flex-grow flex flex-col gap-8">
                    {/* Hero Visual */}
                    <div className="h-[650px] border border-gray-700 bg-black relative shadow-2xl">
                         <VisualGrounding fileData={fileData} boxes={report.detectedObjects} staticMode={true} />
                         <div className="absolute bottom-0 left-0 right-0 bg-black/80 backdrop-blur-md p-4 border-t border-gray-700 flex justify-between items-center">
                             <div>
                                 <span className="text-[10px] font-mono text-gray-500 block">VIBE CODE</span>
                                 <span className="text-xl font-bold text-white uppercase">{report.locationVibe}</span>
                             </div>
                         </div>
                    </div>

                    {/* Key Indices */}
                    <div className="grid grid-cols-3 gap-6">
                        <div className="bg-gray-900/50 p-6 border border-gray-700 backdrop-blur-sm">
                             <div className="text-xs text-gray-500 font-mono mb-2">VIABILITY SCORE</div>
                             <div className="text-7xl font-bold text-signal-green tracking-tighter">{report.viabilityScore}</div>
                        </div>
                        <div className="bg-gray-900/50 p-6 border border-gray-700 backdrop-blur-sm">
                             <div className="text-xs text-gray-500 font-mono mb-2">GENTRIFICATION</div>
                             <div className="text-7xl font-bold text-signal-orange tracking-tighter">{report.gentrificationIndex}</div>
                        </div>
                        <div className="bg-gray-900/50 p-6 border border-gray-700 backdrop-blur-sm">
                             <div className="text-xs text-gray-500 font-mono mb-2">SOCIAL INDEX</div>
                             <div className="text-7xl font-bold text-white tracking-tighter">{report.socialScore}</div>
                        </div>
                    </div>
                </div>
                <PageFooter />
            </div>

            {/* PAGE 2: ENVIRONMENTAL SCAN */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <PageHeader title="ENVIRONMENT" pageNum="02" />
                
                <div className="grid grid-cols-2 gap-10 flex-grow">
                    <div className="flex flex-col gap-8">
                        {/* Map */}
                        <div className="border border-gray-700 h-[400px] bg-gray-900 relative">
                             <GeoMap coordinates={report.coordinates} />
                             <div className="absolute bottom-2 left-2 bg-black/80 px-2 py-1 text-[10px] font-mono text-signal-green">
                                 LAT: {report.coordinates.lat} / LON: {report.coordinates.lng}
                             </div>
                        </div>

                        {/* Radar */}
                        <div className="border border-gray-700 p-6 bg-gray-900/30">
                            <h3 className="font-mono text-xs text-gray-500 mb-6 uppercase tracking-widest border-b border-gray-800 pb-2">Vibe Metrics</h3>
                            <div className="h-[300px]">
                                <RadarAnalysis metrics={report.radarMetrics} />
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col gap-6">
                         {/* Stats Grid */}
                         <div className="grid grid-cols-2 gap-4">
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Architecture</span>
                                <span className="text-sm font-bold">{report.architecturalStyle}</span>
                            </div>
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Atmosphere</span>
                                <span className="text-sm font-bold">{report.atmosphere}</span>
                            </div>
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Density</span>
                                <span className="text-sm font-bold">{report.commercialDensity}</span>
                            </div>
                            <div className="bg-gray-900 p-4 border border-gray-700">
                                <span className="text-[10px] text-gray-500 uppercase block mb-1">Status</span>
                                <span className="text-sm font-bold">{report.constructionStatus}</span>
                            </div>
                         </div>
                         
                         {/* Economics Widget */}
                         <EconomicsWidget latteIndex={report.latteIndex} panopticon={report.panopticonScore} goldenHour={report.goldenHour} />

                         {/* Temporal */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30">
                             <h3 className="font-mono text-xs text-gray-500 mb-6 uppercase tracking-widest border-b border-gray-800 pb-2">Time Travel</h3>
                             <div className="space-y-6">
                                <div>
                                    <span className="text-[10px] text-gray-500 font-mono block mb-2">PAST (-10 YEARS)</span>
                                    <p className="text-sm leading-relaxed border-l-2 border-gray-600 pl-4 text-gray-300">{report.temporalProjection.past}</p>
                                </div>
                                <div>
                                    <span className="text-[10px] text-gray-500 font-mono block mb-2">FUTURE (+10 YEARS)</span>
                                    <p className="text-sm leading-relaxed border-l-2 border-signal-orange pl-4 text-white">{report.temporalProjection.future}</p>
                                </div>
                             </div>
                         </div>
                    </div>
                </div>
                <PageFooter />
            </div>

            {/* PAGE 3: STRATEGY */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <PageHeader title="STRATEGY" pageNum="03" />
                
                <div className="flex-grow flex flex-col gap-8">
                    {/* The Big Idea */}
                    <div className="bg-gray-900 border border-gray-700 p-10 relative overflow-hidden">
                         <InstantIPO recommendation={report.businessRecommendation} />
                    </div>

                    <div className="grid grid-cols-2 gap-8 h-[400px]">
                         {/* Financials */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30 flex flex-col justify-between">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Real Estate Intel</h3>
                             <div className="space-y-6">
                                 <div>
                                     <span className="text-xs text-gray-500">ESTIMATED RENT</span>
                                     <div className="text-3xl font-bold">{report.rentalOpportunity.estimatedRentPerSqFt}</div>
                                 </div>
                                 <div>
                                     <span className="text-xs text-gray-500">VACANCY RISK</span>
                                     <div className={`text-2xl font-bold ${report.rentalOpportunity.vacancyRisk === 'HIGH' ? 'text-red-500' : 'text-green-500'}`}>{report.rentalOpportunity.vacancyRisk}</div>
                                 </div>
                                 <div className="h-24">
                                     <span className="text-xs text-gray-500 block mb-2">GROWTH TREND</span>
                                     <TrendChart />
                                 </div>
                             </div>
                         </div>

                         {/* Pitch */}
                         <div className="border border-gray-700 p-6 bg-white/5">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Investor Pitch</h3>
                             <div className="font-mono text-[11px] text-gray-300 leading-relaxed bg-black p-6 border border-gray-800 h-full overflow-hidden">
                                 <div className="mb-4 text-gray-500 border-b border-gray-800 pb-2">Subject: {report.investorPitch.subjectLine}</div>
                                 {report.investorPitch.emailBody}
                             </div>
                         </div>
                    </div>
                </div>
                <PageFooter />
            </div>

            {/* PAGE 4: CULTURE */}
            <div className="pdf-page bg-anthro-black text-anthro-light p-12 w-[1000px] h-[1414px] relative flex flex-col mb-10 overflow-hidden">
                <PageHeader title="CULTURAL DNA" pageNum="04" />
                
                <div className="flex-grow grid grid-cols-2 gap-10">
                     <div className="flex flex-col gap-8">
                         {/* Persona */}
                         <div className="border border-gray-700 p-8 bg-gray-900 relative overflow-hidden">
                             <User className="absolute top-4 right-4 w-12 h-12 text-gray-800" />
                             <span className="text-signal-orange font-mono text-xs tracking-widest uppercase mb-2 block">Target Persona</span>
                             <h2 className="text-3xl font-bold text-white mb-4">{report.targetPersona.archetype}</h2>
                             <p className="font-serif italic text-xl text-gray-400 mb-6 leading-relaxed">"{report.targetPersona.quote}"</p>
                             <div className="flex flex-wrap gap-2">
                                 {report.targetPersona.accessories.map((item, i) => (
                                     <span key={i} className="px-3 py-1 bg-black border border-gray-700 rounded-full text-xs text-gray-300">{item}</span>
                                 ))}
                             </div>
                         </div>
                         
                         <DatingProfiles profiles={report.datingProfiles} />

                         {/* Demographics */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30 flex-grow">
                             <span className="text-gray-500 font-mono text-xs tracking-widest uppercase mb-4 block">Demographic Split</span>
                             <AnalysisChart data={report.observedDemographics} />
                         </div>
                     </div>

                     <div className="flex flex-col gap-8">
                         {/* Sonic Identity */}
                         <div className="border border-gray-700 p-8 bg-gray-900/50">
                             <h3 className="font-mono text-xs text-gray-500 mb-6 uppercase tracking-widest border-b border-gray-800 pb-2">Sonic Identity</h3>
                             <div className="space-y-6">
                                 {report.playlist.map((track, i) => (
                                     <div key={i} className="flex items-center gap-4">
                                         <div className="w-8 h-8 rounded-full bg-gray-800 flex items-center justify-center text-xs font-mono text-gray-500">{i+1}</div>
                                         <div>
                                             <div className="font-bold text-lg">{track.song}</div>
                                             <div className="text-sm text-gray-400">{track.artist}</div>
                                             <div className="text-[10px] text-signal-orange font-mono uppercase mt-1">{track.vibe}</div>
                                         </div>
                                     </div>
                                 ))}
                             </div>
                         </div>

                         {/* Sensory */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Sensory Profile</h3>
                             <div className="space-y-4">
                                 <div>
                                     <span className="text-[10px] text-gray-500 font-mono block mb-1">SCENT</span>
                                     <p className="text-sm text-white">{report.scentProfile.join(', ')}</p>
                                 </div>
                                 <div>
                                     <span className="text-[10px] text-gray-500 font-mono block mb-1">SOUNDSCAPE</span>
                                     <p className="text-sm text-white">{report.soundscape.join(', ')}</p>
                                 </div>
                             </div>
                         </div>
                         
                         {/* Color Palette */}
                         <div className="border border-gray-700 p-6 bg-gray-900/30">
                             <h3 className="font-mono text-xs text-gray-500 mb-4 uppercase tracking-widest border-b border-gray-800 pb-2">Vibe Palette</h3>
                             <div className="flex h-12 w-full">
                                 {report.colorPalette.map((color, i) => (
                                     <div key={i} className="h-full flex-1" style={{ backgroundColor: color }}></div>
                                 ))}
                             </div>
                         </div>
                     </div>
                </div>
                <PageFooter />
            </div>
        </div>
    );
};
